version: '2'
services:
  Global-LB:
    scale: 1
    start_on_create: false
    lb_config:
      certs: []
      config: "defaults\noption forwardfor\n\nlisten stats \nbind 0.0.0.0:9123\nmode\
        \ http\nstats enable\nstats hide-version\nstats realm Haproxy\\ Statistics\n\
        stats uri /haproxy_stats"
      port_rules:
      - hostname: khhwtml01t.wanhai.com
        path: /collab/ott
        priority: 1
        protocol: http
        service: TML-KHHW/OTT
        source_port: 80
        target_port: 8080
      - hostname: khhwtml01t.wanhai.com
        path: /wanhai/tml/static
        priority: 2
        protocol: http
        service: TML-KHHW/TML-STATIC
        source_port: 80
        target_port: 8080
      - hostname: khhwtml01t.wanhai.com
        path: /wanhai/tml/menu
        priority: 3
        protocol: http
        service: TML-KHHW/TML-MENU
        source_port: 80
        target_port: 8080
      - hostname: khhwtml01t.wanhai.com
        path: /wanhai/tml/cy
        priority: 4
        protocol: http
        service: TML-KHHW/TML-CY
        source_port: 80
        target_port: 8080
      - hostname: txgwtml01t.wanhai.com
        path: /wanhai/tml/static
        priority: 5
        protocol: http
        service: TML-TXGW/TML-STATIC
        source_port: 80
        target_port: 8080
      - hostname: txgwtml01t.wanhai.com
        path: /collab/ott
        priority: 6
        protocol: http
        service: TML-TXGW/OTT
        source_port: 80
        target_port: 8080
      - hostname: txgwtml01t.wanhai.com
        path: /wanhai/tml/menu
        priority: 7
        protocol: http
        service: TML-TXGW/TML-MENU
        source_port: 80
        target_port: 8080
      - hostname: txgwtml01t.wanhai.com
        path: /wanhai/tml/cy
        priority: 8
        protocol: http
        service: TML-TXGW/TML-CY
        source_port: 80
        target_port: 8080
      stickiness_policy:
        cookie: JSESSIONID
        domain: ''
        indirect: true
        mode: prefix
        nocache: true
        postonly: false
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  TeamCity-Agent-Alpha:
    scale: 1
    start_on_create: false
  TML-Docker-Registry:
    scale: 1
    start_on_create: false
  TeamCity-Agent-Beta:
    scale: 1
    start_on_create: false
  TeamCity-Server:
    scale: 1
    start_on_create: false
