version: '3'
services:
  mysql:
    container_name: mysql
    image: "mysql:5.7"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: cattle
      MYSQL_PASSWORD: cattle
      MYSQL_DATABASE: cattle
    volumes:
      - /docker/mysql:/var/lib/mysql
  mysql-admin:
    container_name: mysql-admin
    image: "phpmyadmin/phpmyadmin"
    restart: unless-stopped
    ports:
      - 8222:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - "mysql"
    links:
      - mysql:db  
  # fluent-log:
  #   container_name: fluent-log
  #   image: "fluent/fluentd"
  #   ports:
  #     - 24224:24224
  #     - 24224:24224/udp
  #   volumes:
  #     - /docker/log:/fluentd/log
  #   network_mode: "bridge"   
  rancher-server:
    container_name: rancher-server
    image: "rancher/server"
    restart: unless-stopped
    command: --db-host db
    depends_on:
      - "mysql"
    ports:
      - 8888:8080
    environment:
      DB_HOST: db
    links:
      - mysql:db
