version: '2'
services:
  TML-WS:
    image: khhwtml02t.wanhai.com:8182/wanhai/tml/txgw/uat/tml-ws:latest
    stdin_open: true
    tty: true
    labels:
      io.rancher.scheduler.affinity:host_label: com.wanhai.tml.env=txgw
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
  LB:
    image: rancher/lb-service-haproxy:v0.9.6
    ports:
    - 80:80/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: com.wanhai.tml.env=txgw,com.wanhai.tml.lb_host=true
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
  TML-CY:
    mem_limit: 1073741824
    image: khhwtml02t.wanhai.com:8182/wanhai/tml/txgw/prod/tml-cy:latest
    environment:
      JAVA_OPTS: -Xms1024m -Xmx1024m -XX:MetaspaceSize=96M -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxMetaspaceSize=256m -XX:+UseG1GC -Djava.net.preferIPv4Stack=true  -Djava.awt.headless=true -Dcom.wanhai.tml.yard.current=txgw -Dcom.wanhai.tml.config.env=uat -Dsentry.dsn=http://d5756310a31a47909989df81461b1da1:bfb176b900fb498c8e3b60d31d12c23f@khhwtml02t.wanhai.com:9000/2 -Dsentry.stacktrace.app.packages=com.wanhai.tml -Dsentry.release=0.1.0 -Dsentry.environment=uat
    stdin_open: true
    tty: true
    labels:
      io.rancher.scheduler.affinity:host_label: com.wanhai.tml.env=txgw
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
  TML-MENU:
    mem_limit: 805306368
    image: khhwtml02t.wanhai.com:8182/wanhai/tml/txgw/prod/tml-menu:latest
    environment:
      JAVA_OPTS: -Xms512m -Xmx750m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -XX:+UseG1GC -Djava.net.preferIPv4Stack=true  -Djava.awt.headless=true -Dcom.wanhai.tml.yard.current=txgw -Dcom.wanhai.tml.config.env=uat -Dsentry.dsn=http://d5756310a31a47909989df81461b1da1:bfb176b900fb498c8e3b60d31d12c23f@khhwtml02t.wanhai.com:9000/2 -Dsentry.stacktrace.app.packages=com.wanhai.tml -Dsentry.release=0.1.0 -Dsentry.environment=uat
    stdin_open: true
    tty: true
    labels:
      io.rancher.scheduler.affinity:host_label: com.wanhai.tml.env=txgw
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
  TML-STATIC:
    image: khhwtml02t.wanhai.com:8182/wanhai/tml/txgw/uat/tml-static:latest
    stdin_open: true
    tty: true
    labels:
      io.rancher.scheduler.affinity:host_label: com.wanhai.tml.env=txgw
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
  OTT:
    image: khhwtml02t.wanhai.com:8182/wanhai/tml/txgw/uat/ott:latest
    stdin_open: true
    tty: true
    labels:
      io.rancher.scheduler.affinity:host_label: com.wanhai.tml.env=txgw
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
