version: '2'
services:
  TML-CY:
    scale: 1
    start_on_create: false
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      port: 8080
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 30000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 60000
  TML-MENU:
    scale: 1
    start_on_create: false
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      port: 8080
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 30000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 60000
  TML-STATIC:
    scale: 1
    start_on_create: false
  OTT:
    scale: 1
    start_on_create: false
